### ISSUE TITLE
Can't rename in .vue files

### ISSUE THREAD

**Issue by trickstival** [neoclide/coc-vetur#58]
I have this remap for `coc-rename`:
```vim
nmap <leader>rn <Plug>(coc-rename)
```
When I execute it in .js files, it can rename symbols, but when I try to do it in .vue files, I get this error:
```
[coc.nvim] Rename provider not found for current document
```

It's weird, cause I can rename symbols on vscode in .vue files, but for some reason can't get it working with coc

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by ferrwan** [comment]
Just want to confirm, is the rename function really doesn't work because the vls hasn't supported it yet (https://github.com/vuejs/vetur/issues/610) or there's a miss config?
I'm having problem on this renaming function in file .vue too, other things (jump definition, jump references, snippet, completion) are working nicely though.
![image](https://user-images.githubusercontent.com/14013568/117348799-da145f00-aed4-11eb-8a21-694924c3ffce.png)

**Comment by yaegassy** [comment]
@ferrwan "Rename" is not supported by `vls` itself.
